image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  POSTGRES_DB: reset
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: bleubleu

services:
  - docker:dind

stages:
  - build-frontend
  - build-backend
  - test
  - generate-reports-and-doc

check-frontend:
  stage: .pre
  image: node:lts-alpine
  script:
    - npx prettier@2.0.5 . --check

check-backend:
  stage: .pre
  image: python:3.7-slim
  script:
    - pip3 install black==19.10b0
    - black --check .

compile-frontend:
  stage: build-frontend
  image: node:lts-alpine
  artifacts:
    paths:
      - ftl/frontend/dist
      - ftl/frontend/webpack-stats.json
      - ftl/frontend/node_modules
    expire_in: 7 days
  script:
    - cd ftl/frontend
    - npm ci
    - npm run build

test-frontend-js:
  stage: test
  image: node:lts-alpine
  dependencies:
    - compile-frontend
  artifacts:
    paths:
      - ftl/frontend/coverage
    expire_in: 7 days
  script:
    - cd ftl/frontend
    - npx vue-cli-service test:unit --coverage

compile-backend:
  stage: build-backend
  image: registry.gitlab.com/exotic-matter/ftl-base-image-ci:latest
  dependencies:
    - compile-frontend
  artifacts:
    paths:
      - ftl
      - venv
    expire_in: 7 days
  script:
    - export DJANGO_SETTINGS_MODULE=ftl.settings_tests
    - virtualenv venv && source venv/bin/activate
    - cd ftl && pip3 install -r requirements.txt && pip3 install -r requirements_dev.txt
    - python3 -m compileall ./
    - python3 manage.py compilemessages
    - python3 manage.py collectstatic

test-fast-python:
  stage: test
  image: registry.gitlab.com/exotic-matter/ftl-base-image-ci:latest
  services:
    - postgres:11-alpine
  dependencies:
    - compile-backend
  artifacts:
    paths:
      - ftl/.coverage.*
    expire_in: 7 days
  script:
    - export DJANGO_SETTINGS_MODULE=ftl.settings_tests
    - source venv/bin/activate && cd ftl
    - python3 -m coverage run manage.py test -v 2 --exclude-tag=slow

test-slow-python:
  stage: test
  image: registry.gitlab.com/exotic-matter/ftl-base-image-ci:latest
  services:
    - postgres:11-alpine
  dependencies:
    - compile-backend
  artifacts:
    paths:
      - ftl/.coverage.*
      - ftl/ftests/tests_screenshots
    expire_in: 7 days
  script:
      - export DJANGO_SETTINGS_MODULE=ftl.settings_tests
      - source venv/bin/activate && cd ftl
      - python3 -m coverage run manage.py test -v 2 --tag=slow
  allow_failure: false
  when: manual

python-coverage:
  stage: generate-reports-and-doc
  image: registry.gitlab.com/exotic-matter/ftl-base-image-ci:latest
  services:
    - postgres:11-alpine
  dependencies:
    - compile-backend
    - test-fast-python
    - test-slow-python
  artifacts:
    name: "python_coverage_report"
    paths:
      - ftl/htmlcov
      - ftl/coverage.svg
  script:
      - source venv/bin/activate && cd ftl
      - python3 -m coverage combine
      - python3 -m coverage html
      - python3 -m coverage_badge -o coverage.svg
  allow_failure: true
#  only:
#   - master

javascript-coverage:
  stage: generate-reports-and-doc
  image: node:lts-alpine
  dependencies:
    - compile-frontend
    - test-frontend-js
  artifacts:
    paths:
      - ftl/frontend/coverage/lcov-report
      - ftl/frontend/coverage/badge.svg
    expire_in: 7 days
  script:
    - cd ftl/frontend
    - npx make-coverage-badge
  allow_failure: true
#  only:
#   - master

build-doc:
  stage: generate-reports-and-doc
  image: python:3.7-slim
  artifacts:
    paths:
      - site
  script:
    - pip3 install mkdocs
    - python3 -m mkdocs build
  allow_failure: true
#  only:
#    - master

pages: # Magic job name that publish public folder to Gitlab Pages
  stage: .post
  dependencies:
    - python-coverage
    - javascript-coverage
    - build-doc
  artifacts:
    paths:
      - public # Required to trigger Gitlab Pages publish
  script:
    - mkdir public
    - mv ftl/htmlcov public/python-coverage
    - mv ftl/coverage.svg public/python-coverage.svg
    - mv ftl/frontend/coverage/lcov-report public/javascript-coverage
    - mv ftl/frontend/coverage/badge.svg public/javascript-coverage.svg
    - mv site public/doc
  allow_failure: true
#  only:
#   - master

build-docker-gitlab:
  stage: .post
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  when: manual

build-docker-hub:
  stage: .post
  script:
    - docker login -u $DOCKER_REGISTRY_LOGIN -p $DOCKER_REGISTRY_PASSWORD
    - docker build -t $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $DOCKER_REGISTRY_IMAGE:$CI_COMMIT_TAG
  when: manual
  only:
    - tags
  except:
    - branches
